### ISSUE TITLE
Replies to comments don't appear

### ISSUE THREAD

**Issue by zzkt** [ether/ep_comments#120] opened 2020-05-12 11:45 UTC
Replying to a comment by clicking 'Reply' causes an error and the reply is not displayed. This appears to be the case with Firefox and Chrome (at least) using either 'no-skin' or 'colibris'. 

```
[WARN] client - Uncaught Error: Syntax error, unrecognized expression: # .comment-replies-container -- {
   errorId: 'qsfxwnMjfN78K04XiXPN',
   msg: 'Uncaught Error: Syntax error, unrecognized expression: # .comment-replies-container',
   url: '...',
   linenumber: 9,
   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4140.0 Safari/537.36'
run.sh[24629]: }
```
looks like the `commentId` is not getting set correctly...

**Etherpad version**
Version number: 1.8.3
Git sha: 6210114

**Installed plugins**
ep_comments_page
ep_etherpad-lite
ep_headings2
ep_markdown
ep_page_view

**Comment by JohnMcLear** [comment] 2020-05-12 11:47
Remove ep page view ?

**Comment by zzkt** [comment] 2020-05-12 12:13
just saw the `DEFUNCT PLUGIN:`warning so it's disabled now. I also disabled all other plugins to test it and no change. BUT, adding and replying to comments works on newly created pad. 

So, looks like this error is only happening on pads that existed before upgrading to 1.8.3

**Comment by JohnMcLear** [comment] 2020-05-12 12:17
Ah bummer.  Any idea @seballot ?

**Comment by zzkt** [comment] 2020-05-12 12:23
I don't get any errors from the `checkAllPads.js` script but testing what happens with `rebuildPad.js`

**Comment by JohnMcLear** [comment] 2020-05-12 13:11
@zzkt I think it's related to how userId is set since changes in 1.8.3, I will try take a look.  Is this a fire for you?  I have other issues I want to get to first.

**Comment by zzkt** [comment] 2020-05-12 13:15
Thanks @JohnMcLear there's no immediate rush but would be great to have it fixed. Can you suggest any possible workarounds?

**Comment by JohnMcLear** [comment] 2020-05-12 13:15
No, sorry, not without breaking off what I'm doing.

**Comment by seballot** [comment] 2020-05-12 14:47
Hi ! I just did some testing, switching back to version 0.0.35 (before my refactoring), adding a comment, then switch to master, I can still open and reply to the comment. So I cannot manage to reproduce :/

But I found the line of code which is raising this error, it seems in your database you have comment replies without the reference to the comment Id... From what I understand, everytime we do add one reply, it redraws all the replies for all comments, so even if the problem is on a comment different the one you try to reply, it fails. I made a fix for that. Hope this will be enough !

**Comment by JohnMcLear** [comment] 2020-05-12 15:03
I merged the fixes into master, please confirm @zzkt that this fixes and I will publish a release.

**Closed** 2020-05-12 15:03 UTC

**Comment by zzkt** [comment] 2020-05-12 15:46
Thanks @seballot & @JohnMcLear it's looking good.

**Comment by JohnMcLear** [comment] 2020-05-12 16:11
published.
